"""Remove red/template divider backgrounds from generated presentation slides.

This patches the current latest completed deck, preserving slide order and any
slides not generated by Codex. It adds a white background rectangle behind the
content on the generated result/modified/MediaPipe slides so they use the same
white content-slide style as the methodology pages.
"""

from pathlib import Path

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE


INPUT = Path("presentation/AI_LAB_expai_presentation_ACSAI_2025_2026_completed_template_style.pptx")
OUTPUT = Path("presentation/AI_LAB_expai_presentation_ACSAI_2025_2026_no_red_backgrounds.pptx")

TARGET_TITLES = {
    "Results roadmap",
    "The dataset is usable, but not equally complete",
    "Agreement replaces accuracy in this study",
    "Average emotion profiles reveal model bias patterns",
    "Human ratings are multi-dimensional, not single labels",
    "Dominant-emotion matrices show where humans and models collide",
    "Agreement varies by intended emotion category",
    "Modified images test stability under visual change",
    "Blur affects DeepFace more than greyscale",
    "Greyscale makes human responses more mixed",
    "Ambiguous images lower agreement and increase uncertainty",
    "MediaPipe links emotion scores to facial movement features",
    "Human ratings connect to intuitive facial features",
    "FER associations emphasize classic expression cues",
    "DeepFace uses facial cues but aligns less with humans overall",
}


def slide_texts(slide):
    return [getattr(shape, "text", "").strip() for shape in slide.shapes]


def send_to_back(slide, shape):
    tree = slide.shapes._spTree
    element = shape.element
    tree.remove(element)
    # p:spTree starts with nvGrpSpPr and grpSpPr. Insert after those so the
    # background stays behind all visible content.
    tree.insert(2, element)


def add_white_background(slide, prs):
    bg = slide.shapes.add_shape(
        MSO_SHAPE.RECTANGLE,
        0,
        0,
        prs.slide_width,
        prs.slide_height,
    )
    bg.fill.solid()
    bg.fill.fore_color.rgb = RGBColor(255, 255, 255)
    bg.line.fill.background()
    send_to_back(slide, bg)


def main():
    prs = Presentation(str(INPUT))
    patched = 0

    for slide in prs.slides:
        texts = set(slide_texts(slide))
        if texts & TARGET_TITLES:
            add_white_background(slide, prs)
            patched += 1

    prs.save(str(OUTPUT))
    print(f"Patched {patched} generated slides")
    print(f"Saved {OUTPUT.resolve()}")


if __name__ == "__main__":
    main()
